// lit-html/src/App.js
import {html, render} from 'lit-html';
import LitComponent from './LitComponent.js';
import Calendar from './Calendar.js';
import {range} from './common/utils.js';
import TestRunner from './common/test_runner.js';


class App extends LitComponent {

  static get DISPLAY_CALENDARS () {
    return 'display-calendars';
  }
  constructor() {
    super();
    this.state = {count: 1, time: 0};
    this.handleClick = this.handleClick.bind(this);
    this.showTime = this.showTime.bind(this);
    this.displayTime_ = new DisplayTime();
    this.calendars_ = [];
    new TestRunner(document.querySelector('h3'));
  }

  onFirstCreation(container) {
    container.querySelector('#test-buttons').addEventListener(
        'click', event => this.handleClick(event));
  }

  handleClick(event) {
    if (event.target.dataset.handler === undefined) {
      return;
    }
    const t = window.performance.now();
    this.setState({count: Number.parseInt(event.target.value, 10)});
    setTimeout(() => this.showTime(window.performance.now() - t), 1);
  }

  showTime(time) {
    document.dispatchEvent(new CustomEvent('log-time', {detail: time}));
    this.displayTime_.showTime(time);
    //this.setState({time: time});
  }

  getHtml() {
    const testButtons =
        [0, 1, 2, 3, 5, 10, 50, 100].map(value => this.renderButton(value));
    const time =
        this.state.time > 0 ? `${this.state.time.toFixed(2)} milliseconds` : '';
    while (this.calendars_.length < this.state.count) {
      this.calendars_.push(new Calendar(this.showTime).render());
    }
    while (this.calendars_.length > this.state.count) {
      this.calendars_.pop();
    }
    return html`
        <div id="test-buttons">
          ${testButtons}
          ${this.displayTime_.render()}
        </div>
        ${this.calendars_}
        `;
  }

  renderButton(value) {
    return html `
        <button data-handler=${App.DISPLAY_CALENDARS}
                value=${value}
                title=${`Display ${value} calendars`} >
          ${String(value)}
        </button>`;
  }
}

class DisplayTime extends LitComponent {
    constructor() {
    super();
    this.state = {time: 0};


  }

  showTime(time) {
    this.setState({time: time});
  }

  getHtml() {

    const time =
        this.state.time > 0 ? `${this.state.time.toFixed(2)} milliseconds` : '';
    return html` <div key="time-display" id="time-display">${time}</div> `;
  }
}

export default App;

// react/src/App.js
import "./common/polyfills";
import React, { Component } from "react";
import Calendar from "./Calendar";
import { range } from "./common/utils";
import TestRunner from './common/test_runner.js';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { count: 1, time: "" };
    this.handleClick = this.handleClick.bind(this);
    this.showTime = this.showTime.bind(this);
    new TestRunner(document.querySelector('h3'));
  }

  handleClick(event) {
    const t = window.performance.now();
    this.setState({ count: Number.parseInt(event.target.value, 10) });
    setTimeout(() => this.showTime(window.performance.now() - t), 1);
  }

  showTime(time) {
    document.dispatchEvent(new CustomEvent('log-time', {detail: time}));
    this.setState({ time: time });
  }

  render() {
    const calendars = Array.from(range(this.state.count)).map(index => (
      <Calendar key={index} showTime={this.showTime} />
    ));
    const testButtons = [0, 1, 2, 3, 5, 10, 50, 100].map(value => (
      <TestButton key={value} onClick={this.handleClick} value={`${value}`} />
    ));
    const time =
      this.state.time > 0 ? `${this.state.time.toFixed(2)} milliseconds` : "";
    return [
      <div key="test-buttons" id="test-buttons">
        {testButtons}
        <div key="time-display" id="time-display">
          {time}
        </div>
      </div>,
      calendars
    ];
  }
}

var TestButton = props => {
  const { onClick, value } = props;
  return (
    <button
      key={value}
      {...{ onClick, value }}
      title={`Display ${value} calendars`}
    >
      {value}
    </button>
  );
};

export default App;
